<a href="https://colab.research.google.com/github/dilp90/InteligenciaArtificial_y_RedesNeuronales_UANL_FIME/blob/main/3_Librerias_UsoDeNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tutorial para librería Numpy**

NumPy es el paquete fundamental para la computación científica en Python. Es una biblioteca de Python que proporciona un objeto de matriz multidimensional, varios objetos derivados (como matrices y matrices enmascaradas) y una variedad de rutinas para operaciones rápidas en matrices, incluidas operaciones matemáticas, lógicas, manipulación de formas, ordenamiento, selección, E/S, transformadas discretas de Fourier, álgebra lineal básica, operaciones estadísticas básicas, simulación aleatoria y mucho más.

En el núcleo del paquete NumPy se encuentra el objeto `ndarray`. Este encapsula matrices n-dimensionales de tipos de datos homogéneos, y muchas operaciones se realizan en código compilado para mejorar el rendimiento.

**Ejercicio**:  

Manipulación y análisis de matrices con NumPy para Inteligencia Artificial

**Objetivo:**

Familiarizarse con el uso de NumPy para la manipulación y análisis de matrices, librería que facilita el trabajo con grandes volúmenes de datos y redes neuronales en proyectos de inteligencia artificial.

**1. Importar librerías**

In [1]:
import numpy as np

**2. Crear y explorar matrices:**

* Crea una matriz de 3x3 con valores aleatorios entre 0 y 1:

In [2]:
matrix_a = np.random.rand(3, 3)
print("Matriz A:")
print(matrix_a)

Matriz A:
[[0.34663689 0.36154821 0.02425528]
 [0.41466461 0.31079971 0.98385883]
 [0.64758071 0.40953878 0.94821872]]


* Crea una matriz identidad de tamaño 3x3:

In [3]:
identity_matrix = np.eye(3)
print("Matriz Identidad:")
print(identity_matrix)

Matriz Identidad:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


* Crea una matriz de unos de tamaño 2x4:

In [4]:
ones_matrix = np.ones((2, 4))
print("Matriz de Unos:")
print(ones_matrix)

Matriz de Unos:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


3. Operaciones básicas de matrices:

* Suma de matrices: Crea otra matriz de 3x3 y súmala con la primera:

In [5]:
matrix_b = np.random.rand(3, 3)
sum_matrix = matrix_a + matrix_b
print("Suma de Matrices A y B:")
print(sum_matrix)

Suma de Matrices A y B:
[[1.34379384 0.68205732 0.91700607]
 [0.82910528 1.13642545 1.68640504]
 [0.67994925 1.15680957 1.25162641]]


* Producto de matrices (multiplicación de matrices):

In [6]:
product_matrix = np.dot(matrix_a, matrix_b)
print("Producto de Matrices A y B:")
print(product_matrix)

Producto de Matrices A y B:
[[0.49627677 0.42772905 0.57082392]
 [0.5741398  1.124717   0.88705365]
 [0.84616158 1.25425744 1.15354496]]


* Transposición de una matriz:

In [7]:
transposed_matrix = np.transpose(matrix_a)
print("Matriz Transpuesta de A:")
print(transposed_matrix)

Matriz Transpuesta de A:
[[0.34663689 0.41466461 0.64758071]
 [0.36154821 0.31079971 0.40953878]
 [0.02425528 0.98385883 0.94821872]]


4. Acceso y manipulación de elementos:

* Accede al elemento en la fila 2, columna 3 de `matrix_a`:

In [8]:
element = matrix_a[1, 2]  # Recuerda que el índice empieza desde 0
print("Elemento en fila 2, columna 3 de A:", element)

Elemento en fila 2, columna 3 de A: 0.9838588333370378


* Cambia el valor en la fila 1, columna 2 de matrix_a a 5:

In [9]:
matrix_a[0, 1] = 5
print("Matriz A con valor modificado:")
print(matrix_a)

Matriz A con valor modificado:
[[0.34663689 5.         0.02425528]
 [0.41466461 0.31079971 0.98385883]
 [0.64758071 0.40953878 0.94821872]]


5. Operaciones estadísticas:

* Calcula el valor máximo, mínimo y la media de la matriz `matrix_a`:

In [10]:
print("Valor máximo de A:", np.max(matrix_a))
print("Valor mínimo de A:", np.min(matrix_a))
print("Media de A:", np.mean(matrix_a))

Valor máximo de A: 5.0
Valor mínimo de A: 0.02425528315519132
Media de A: 1.009505949590808


6. Reducción de dimensiones:

* Convierte una matriz 2D (3x3) en un vector (1D) de 9 elementos:

In [11]:
flattened_matrix = matrix_a.flatten()
print("Matriz A a vector 1D:")
print(flattened_matrix)

Matriz A a vector 1D:
[0.34663689 5.         0.02425528 0.41466461 0.31079971 0.98385883
 0.64758071 0.40953878 0.94821872]


7. Aplicaciones prácticas para AI:

* *Normalización de Datos*: Supón que tienes un conjunto de datos con características (por ejemplo, una matriz de características de 3x3). Normaliza los valores de cada columna para que tengan una media de 0 y una desviación estándar de 1.

In [12]:
data = np.random.rand(3, 3) * 100  # Datos aleatorios
print("Datos originales:")
print(data)

normalized_data = (data - np.mean(data, axis=0)) / np.std(data, axis=0)
print("Datos normalizados:")
print(normalized_data)

Datos originales:
[[53.7929529  74.99463647 22.20972195]
 [99.50645331 43.62150664 11.51662698]
 [87.23984444 10.53604288 73.17874057]]
Datos normalizados:
[[-1.36587247  1.21375706 -0.49900893]
 [ 1.00041742  0.02168757 -0.89646349]
 [ 0.36545505 -1.23544463  1.39547243]]


Fuentes:

*   https://numpy.org/devdocs/user/whatisnumpy.html#whatisnumpy





M.Sc. Daniel I. Lopez-Paez

Clase: Inteligencia Artificial y Redes Neuronales

PE: Ingeniería en Mecatrónica

FIME-UANL